name: e2e tests

on:
  push:
    branches: [alpha]
  pull_request:
    branches: [alpha]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create ENV File
        run: |
          cd server
          touch .env
          echo ${{ secrets.ENV_VARS }} | base64 -d > .env
      - run: npm run ipkgs
      - run: cd client && npm run build
      - run: npm run e2e-test

  merge-branch:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge alpha -> main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: main
          github_token: ${{ secrets.GH_TOKEN }}
